// <auto-generated />
namespace Journey.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Hopefully_Solved_Puzzle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Hopefully_Solved_Puzzle));
        
        string IMigrationMetadata.Id
        {
            get { return "201706111348274_Hopefully_Solved_Puzzle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
