// <auto-generated />
namespace Journey.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_IsDefault_Property_To_Vehicle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_IsDefault_Property_To_Vehicle));
        
        string IMigrationMetadata.Id
        {
            get { return "201708031534406_Added_IsDefault_Property_To_Vehicle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
