// <auto-generated />
namespace Journey.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edited_Vehicle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edited_Vehicle));
        
        string IMigrationMetadata.Id
        {
            get { return "201707241200476_edited_Vehicle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
