// <auto-generated />
namespace Journey.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_trips_to_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_trips_to_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201706111012131_added_trips_to_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
